services:
  staff:
    build: ./staff
    volumes:
      - ./staff:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    env_file:
      - ./staff/.env
    command: node --watch src/index.js
    extra_hosts:
      - "domain:XX.X.X.XX"
    networks:
      - ms-ns-network
      - sst-network

  reports-manager:
    build: ./reports-manager
    volumes:
      - ./reports-manager:/app
      - /app/node_modules/
    ports:
      - "3003:3003"
    env_file:
      - ./reports-manager/.env
    command: npm run dev
    extra_hosts:
      - "domain:XX.X.X.XX"
    networks:
      - ms-ns-network
      - sst-network

  nginx:
    image: nginx:latest
    container_name: API-SST-GATEWAY
    ports:
      - "8001:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - staff
      - reports-manager
    networks:
      - sst-network
      
networks:
  ms-ns-network:
    external: true
    driver: bridge
    
  sst-network:
    external: true
    driver: bridge
