services:
  staff:
    build: ./staff
    volumes:
      - ./staff:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    env_file:
      - ./staff/.env
    command: node --watch src/index.js
    extra_hosts:
      - "domain:XX.X.X.XX"
    networks:
      - shared-network

  reports-manager:
    build: ./reports-manager
    volumes:
      - ./reports-manager:/app
      - /app/node_modules
    ports:
      - "3003:3003"
    env_file:
      - ./reports-manager/.env
    command: npm run dev
    extra_hosts:
      - "domain:XX.X.X.XX"
    networks:
      - shared-network
      
networks:
  shared-network:
    driver: bridge
